{
 "title": "Worldwide Status",
 "time": { "from": "2020-01-15T13:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Case Reports By Time",
   "type": "graph",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Confirmed\" FROM \"autogen\".\"WorldWide\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Recovered\" FROM \"autogen\".\"WorldWide\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Deaths\" FROM \"autogen\".\"WorldWide\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Confirmed\") FROM \"autogen\".\"WorldWide\" WHERE (\"Country\" = 'Global') AND $timeFilter",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT mean(\"Recovered\") FROM \"autogen\".\"WorldWide\" WHERE (\"Country\" = 'Global') AND $timeFilter ",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WorldWide",
     "query": "SELECT mean(\"Deaths\") FROM \"autogen\".\"WorldWide\" WHERE (\"Country\" = 'Global') AND $timeFilter ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "All" }
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT mean(\"Confirmed\") FROM \"autogen\".\"WorldWide\" WHERE  $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Recovered\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Deaths\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}