{
 "title": "Status By Country",
 "tags": [ "Country" ],
 "time": { "from": "2020-01-15T13:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "country_name",
    "label": "Select a country",
    "query": "SELECT distinct(\"Country\")  FROM \"covid19\".\"autogen\".\"ByCountry\""
   }
  ]
 },
 "panels": [
  {
   "title": "$country_name Overview",
   "type": "graph",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Confirmed\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP By time(24h)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Recovered\")   FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP By time(24h)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT        max( \"Deaths\")   FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP By time(24h)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Confirmed\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered vs Deaths",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Recovered\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Deaths\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Deaths" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=~", "value": "/^$country_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Recovered\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Deaths\") FROM \"autogen\".\"ByCountry\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "$country_name daily cases",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Value\") FROM \"autogen\".\"graph-cases-daily\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "US" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"Value\") FROM \"autogen\".\"graph-deaths-daily\" WHERE (\"Country\" =~ /^$country_name$/) AND $timeFilter GROUP BY time(24h)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}