{
 "title": "Australia By State",
 "time": { "from": "2020-01-15T13:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "State",
    "query": "SELECT State_Province FROM autogen.Cases WHERE  Country = 'Australia'"
   }
  ]
 },
 "panels": [
  {
   "title": "$state Overview",
   "type": "graph",
   "gridPos": { "h": 16, "w": 16, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Confirmed\"   FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Recovered\"   FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT \"Deaths\"   FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    }
   ]
  },
  {
   "title": "Confirmed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Confirmed\") FROM \"autogen\".\"Australia\" WHERE  $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    }
   ]
  },
  {
   "title": "Recovered",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT max(\"Recovered\") FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "Recovered" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"Deaths\") FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter AND (\"State\" =~ /^$state$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Confirmed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ByCountry",
     "query": "SELECT mean(\"Confirmed\") FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter and (State =~ /^$state$/) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ],
      [
       { "params": [ "Confirmed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Australia" }
     ]
    },
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Recovered\") FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter and (State =~ /^$state$/) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"Deaths\") FROM \"autogen\".\"Cases\" WHERE (\"Country\" = 'Australia') AND $timeFilter and (State =~ /^$state$/) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}