{
 "title": "By Geo location",
 "description": "View Worldmap virus distribution",
 "tags": [ "map" ],
 "time": { "from": "2020-01-19T13:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Total Case",
   "type": "stat",
   "description": "Display total global confirmed cases",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Total Cases",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coronavirus-cases-linear",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "stat",
   "description": "Display total global confirmed cases",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "targets": [
    {
     "alias": "Total Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coronavirus-deaths-linear",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Serious Cases",
   "type": "stat",
   "description": "Display total global confirmed cases",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Serious Cases",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total-serious-linear",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Recovered Cases",
   "type": "stat",
   "description": "Display total global recovered cases",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 0 },
   "targets": [
    {
     "alias": "Total Cases",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graph-cured-total",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Recovered/Death rate",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "alias": "Recovered",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graph-cured-total",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    },
    {
     "alias": "Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "coronavirus-deaths-linear",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Active cases",
   "type": "stat",
   "description": "Display total global confirmed cases",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "targets": [
    {
     "alias": "Total Deaths",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graph-active-cases-total",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Serious/Actives",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "alias": "Active",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "graph-active-cases-total",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    },
    {
     "alias": "Serious",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "total-serious-linear",
     "select": [
      [
       { "params": [ "Value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "Country", "operator": "=", "value": "Global" }
     ]
    }
   ]
  },
  {
   "title": "Data table",
   "type": "table",
   "gridPos": { "h": 24, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(Confirmed) as Count FROM \"autogen\".\"Cases\" WHERE  $timeFilter GROUP BY Country",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "View By Location ",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 20, "w": 19, "x": 0, "y": 4 },
   "valueName": "max",
   "targets": [
    {
     "alias": "Count",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "Cases",
     "query": "SELECT max(Confirmed) as Count, geohash as geohash ,geoname as geoname FROM \"autogen\".\"Cases\" WHERE  $timeFilter GROUP BY Country , geohash",
     "select": [
      [
       { "params": [ "Confirmed" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Count" ], "type": "alias" }
      ],
      [
       { "params": [ "geohash" ], "type": "field" },
       { "params": [ "geohash" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "geohash", "operator": "!=", "value": "'0'" },
      { "condition": "AND", "key": "Country", "operator": "=", "value": "Austria" }
     ]
    }
   ]
  }
 ]
}